// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace HomeAccountingDAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeAccountingDAL.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cellular Service"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Internet"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("HomeAccountingDAL.Data.Entities.ExpensesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("money");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Comment = "Ate 3 hamburgers with friends",
                            Cost = 120m,
                            Date = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "McDonalds"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Cost = 200m,
                            Date = new DateTime(2023, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "lifecell"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Comment = "Took Uklon taxi for home",
                            Cost = 185m,
                            Date = new DateTime(2023, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Taxi"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Cost = 320m,
                            Date = new DateTime(2023, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cafe"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Comment = "Shevchenko street",
                            Cost = 244m,
                            Date = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Triolan"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Comment = "Parent's house",
                            Cost = 150m,
                            Date = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maxnet"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Comment = "Bought yet another CSGO copy in Steam",
                            Cost = 550m,
                            Date = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CSGO"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Cost = 59m,
                            Date = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lays Crisps"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Cost = 139m,
                            Date = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spotify subscription"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Cost = 229m,
                            Date = new DateTime(2023, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MEGOGO subscription"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Comment = "Year prepaid for mom",
                            Cost = 2285m,
                            Date = new DateTime(2023, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vodafone"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Cost = 20m,
                            Date = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bus"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Cost = 150m,
                            Date = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Salami"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Comment = "Zoo near the forest",
                            Cost = 450m,
                            Date = new DateTime(2023, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Zoo"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Cost = 16m,
                            Date = new DateTime(2023, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tram"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Comment = "Bought food for the holiday",
                            Cost = 690m,
                            Date = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ekomarket"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Comment = "247e",
                            Cost = 24m,
                            Date = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bus"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Cost = 14.8m,
                            Date = new DateTime(2023, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ice cream"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Cost = 1350m,
                            Date = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Metallica concert tickets"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Comment = "Bought in Origin",
                            Cost = 160m,
                            Date = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PES2009"
                        });
                });

            modelBuilder.Entity("HomeAccountingDAL.Data.Entities.ExpensesEntity", b =>
                {
                    b.HasOne("HomeAccountingDAL.Data.Entities.CategoryEntity", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HomeAccountingDAL.Data.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
